# 1.2 Ethics and Directionn of Machine Learning Programs

In [1]:
#importing dataframes 
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import StandardScaler

In [2]:
#creating a path 
path = r"/Users/tiffanib./Desktop/Career Foundry Data Analytics/Machine Learning with Python/Data Sets/"

In [3]:
path

'/Users/tiffanib./Desktop/Career Foundry Data Analytics/Machine Learning with Python/Data Sets/'

In [4]:
#importing Data Set
df = pd.read_csv(os.path.join(path, "Dataset-weather-prediction-dataset-processed.csv"))

In [5]:
df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [6]:
df.shape

(22950, 170)

In [7]:
#checking missing values
df.isnull().sum().sum()

np.int64(0)

In [8]:
#excluding these columns from scaling
exclude_cols = ['DATE', 'MONTH',]
exclude_cols = [c for c in exclude_cols if c in df.columns]
exclude_cols

['DATE', 'MONTH']

In [9]:
#builing the ones that will be scaled
scale_cols = [c for c in df.columns if c not in exclude_cols]
len(scale_cols), scale_cols[:10]

(168,
 ['BASEL_cloud_cover',
  'BASEL_wind_speed',
  'BASEL_humidity',
  'BASEL_pressure',
  'BASEL_global_radiation',
  'BASEL_precipitation',
  'BASEL_snow_depth',
  'BASEL_sunshine',
  'BASEL_temp_mean',
  'BASEL_temp_min'])

In [10]:
#creating the scaler
scaler = StandardScaler()

In [11]:
#scaling columns
df_scaled = df.copy()
df_scaled[scale_cols] = scaler.fit_transform(df[scale_cols])
df_scaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,0.660514,-0.02793,0.826097,-0.001949,-1.101066,-0.265148,-0.179228,-0.902918,...,-0.443701,0.761754,-1.299744,-0.806427,-0.088407,-0.024706,0.372147,-0.668215,-0.519743,-0.752237
1,19600102,1,0.244897,-0.02793,0.735760,-0.001949,-1.058108,1.658760,-0.179228,-0.810126,...,0.783085,1.183580,-1.262455,-1.042055,0.503361,-0.024706,-0.829285,-0.548046,-0.629054,-0.407141
2,19600103,1,1.076130,-0.02793,1.277781,-0.001949,-1.251420,0.155707,-0.179228,-1.065304,...,0.783085,1.183580,-0.432779,-1.136306,-0.396127,-0.024706,-1.009500,-0.067372,0.054135,-0.177078
3,19600104,1,-1.001953,-0.02793,1.458455,-0.001949,-0.821838,-0.445514,-0.179228,-0.114186,...,0.783085,0.480538,0.387574,-1.183432,0.669056,-0.024706,-1.039536,-0.998679,-0.164486,-0.838511
4,19600105,1,0.244897,-0.02793,1.729466,-0.001949,-0.746661,-0.164944,-0.179228,0.187388,...,-1.670486,-0.363113,1.729970,-0.794645,-0.490810,-0.024706,0.672505,-1.509396,-1.339569,-1.471186

In [14]:
#Checking values of the mean for the scaled variables
df_scaled[scale_cols].mean().head().round(4)

BASEL_cloud_cover        -0.0
BASEL_wind_speed         -0.0
BASEL_humidity            0.0
BASEL_pressure           -0.0
BASEL_global_radiation   -0.0
dtype: float64

In [15]:
#verifying scaling by checking the standard deviation of scaled variables
df_scaled[scale_cols].std(ddof=0).head().round(4)

BASEL_cloud_cover         1.0
BASEL_wind_speed          1.0
BASEL_humidity            1.0
BASEL_pressure            1.0
BASEL_global_radiation    1.0
dtype: float64

In [16]:
#Exporting scaled dataframe 
output_name = "Dataset-weather-prediction-dataset-processed_scaled.csv"
df_scaled.to_csv(os.path.join(path, output_name), index=False)

os.path.join(path, output_name)

'/Users/tiffanib./Desktop/Career Foundry Data Analytics/Machine Learning with Python/Data Sets/Dataset-weather-prediction-dataset-processed_scaled.csv'